### ISSUE TITLE
can't run api node/broker 

### ISSUE THREAD

**Issue by mliang-circle** [symbol/catapult-client#144]
Hi! I have following the docs build symbol-server myself. But I can't run api node, the broker script.
This is the error message I see
```
2021-01-17 02:56:29.750350 0x00007f66a9a5a4c0: <info> (thread::IoThreadPool.cpp@105) spawned 8 workers (broker) 
2021-01-17 02:56:29.750447 0x00007f66a9a5a4c0: <info> (plugins::PluginModule.cpp@83) loading plugin from ../lib/libextension.addressextraction.so 
2021-01-17 02:56:29.750980 0x00007f66a9a5a4c0: <info> (extensions::ProcessBootstrapper.cpp@121) registering dynamic extension extension.addressextraction 
2021-01-17 02:56:29.751101 0x00007f66a9a5a4c0: <info> (plugins::PluginModule.cpp@83) loading plugin from ../lib/libextension.mongo.so 
2021-01-17 02:56:29.752100 0x00007f66a9a5a4c0: <error> (plugins::PluginModule.cpp@94) Throwing exception: unable to find plugin (../lib/libextension.mongo.so) 
2021-01-17 02:56:29.752327 0x00007f66a9a5a4c0: <fatal> (process::ProcessMain.cpp@75) 
thread: broker catapult
unhandled exception while running local node!
../src/catapult/plugins/PluginModule.cpp(94): Throw in function catapult::plugins::PluginModule::PluginModule(const string&, const string&, catapult::plugins::PluginModule::Scope)
Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::invalid_argument> >
std::exception::what: unable to find plugin
[catapult::ErrorParam1*] = ../lib/libextension.mongo.so
```
I did look for `libextension.mongo.so` file in my workspace, and it is in the right path. I don't understand why it can't find plugin  (../lib/libextension.mongo.so) 

I use conan build and peer node works fine. Please let me know how to troubleshoot. Thanks!

**Comment by Jaguar0625** [comment]
what OS / complier?

**Comment by mliang-circle** [comment]
I built in  ubuntu:20.10 and gcc9

**Comment by Wayonb** [comment]
Does your LD_LIBRARY_PATH including the ``deps`` folder from the conan build?

Can you check which libraries are missing?
````
 ldd libextension.mongo.so
 ````

**Comment by mliang-circle** [comment]
LD_LIBRARY_PATH includes `deps` not help.

When I get into `lib` folder and ` ldd libextension.mongo.so`, this is the result:

```
root@47f37e2db5a2:/lib# cd /home/server/_build/lib/
root@47f37e2db5a2:/home/server/_build/lib# ldd libextension.mongo.so
        linux-vdso.so.1 (0x00007ffdc29d9000)
        libboost_log.so.1.75.0 => /home/server/_build/deps/libboost_log.so.1.75.0 (0x00007f5891c57000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5891c35000)
        libmongocxx.so._noabi => /home/server/_build/deps/libmongocxx.so._noabi (0x00007f5891b86000)
        libbsoncxx.so._noabi => /home/server/_build/deps/libbsoncxx.so._noabi (0x00007f5891b62000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5891b5c000)
        librocksdb.so.6 => /home/server/_build/deps/librocksdb.so.6 (0x00007f58913f0000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f5891111000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5890f30000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5890f15000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5890d2b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5891f3b000)
        libboost_filesystem.so.1.75.0 => /home/server/_build/deps/libboost_filesystem.so.1.75.0 (0x00007f5890d0a000)
        libboost_thread.so.1.75.0 => /home/server/_build/deps/libboost_thread.so.1.75.0 (0x00007f5890ced000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5890ce0000)
        libmongoc-1.0.so.0 => /root/.conan/data/mongo-c-driver/1.17.2/nemtech/stable/package/a22735de389baa9bdc6de5ac838f516e1c44d98d/lib/libmongoc-1.0.so.0 (0x00007f5890c33000)
        libbson-1.0.so.0 => /root/.conan/data/mongo-c-driver/1.17.2/nemtech/stable/package/a22735de389baa9bdc6de5ac838f516e1c44d98d/lib/libbson-1.0.so.0 (0x00007f5890bf1000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5890aa2000)
        libssl.so.1.1 => /root/.conan/data/openssl/1.1.1g/nemtech/stable/package/a047379cdfd402188b892e25d26513e6c5221a79/lib/libssl.so.1.1 (0x00007f5890a09000)

```

**Comment by Wayonb** [comment]
Are you getting the same load error?
Looking at the ldd output above all the external libraries can be resolved.
Also noticed that your LD_LIBRARY_PATH has paths to ``/root/.conan`` which is not needed.  All the dependencies should be in the ``deps`` folder.

**Comment by mliang-circle** [comment]
how you determine  that my LD_LIBRARY_PATH is ·/root/.conan`, not `deps` folder

**Comment by Jaguar0625** [comment]
libmongoc-1.0.so.0 => **/root/.conan/** data/mongo-c-driver/1.17.2/nemtech/stable/package/a22735de389baa9bdc6de5ac838f516e1c44d98d/lib/libmongoc-1.0.so.0 (0x00007f5890c33000)

**Comment by Jaguar0625** [comment]
@mliang-circle - are you still having problems?

**Comment by Jaguar0625** [comment]
Please reopen if there are still issues.

**Comment by tqm-dev** [comment]
Same problem here..

I see my libextension.mongo.so is  in _build/lib but getting this error:

```
2021-11-29 17:02:44.981252 0x00007f32ee0ba140: <info> (thread::IoThreadPool.cpp@105) spawned 4 workers (broker) 
2021-11-29 17:02:44.981655 0x00007f32ee0ba140: <info> (plugins::PluginModule.cpp@83) loading plugin from ../lib/libextension.addressextraction.so 
2021-11-29 17:02:44.982900 0x00007f32ee0ba140: <info> (extensions::ProcessBootstrapper.cpp@121) registering dynamic extension extension.addressextraction 
2021-11-29 17:02:44.983026 0x00007f32ee0ba140: <info> (plugins::PluginModule.cpp@83) loading plugin from ../lib/libextension.mongo.so 
2021-11-29 17:02:44.983741 0x00007f32ee0ba140: <error> (plugins::PluginModule.cpp@94) Throwing exception: unable to find plugin (../lib/libextension.mongo.so) 
2021-11-29 17:02:44.983987 0x00007f32ee0ba140: <fatal> (process::ProcessMain.cpp@75) 
thread: broker catapult
unhandled exception while running local node!
../src/catapult/plugins/PluginModule.cpp(94): Throw in function catapult::plugins::PluginModule::PluginModule(const string&, const string&, catapult::plugins::PluginModule::Scope)
Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::invalid_argument> >
std::exception::what: unable to find plugin
[catapult::ErrorParam1*] = ../lib/libextension.mongo.so
 
Aborted (core dumped)

```
OS:Ubuntu 20.04.3 LTS
Compiler gcc-9 g++-9
I am following the setup processes:
https://docs.symbolplatform.com/guides/network/running-a-symbol-node-manually.html

Thanks

**Comment by tqm-dev** [comment]
@Jaguar0625 

I need your help.
Could you open it again ?

**Comment by tqm-dev** [comment]
$ ldd libextension.mongo.so

getting the result here:

	linux-vdso.so.1 (0x00007ffd4a14f000)
	libmongocxx.so._noabi => not found
	libbsoncxx.so._noabi => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6fd4ac6000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f6fd47f0000)
	libboost_log.so.1.76.0 => /home/tqm-dev/projects/catapult-client/_deps/boost/lib/libboost_log.so.1.76.0 (0x00007f6fd471a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6fd46f5000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6fd4513000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6fd44f8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6fd4306000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6fd4ce0000)
	libboost_thread.so.1.76.0 => /home/tqm-dev/projects/catapult-client/_deps/boost/lib/libboost_thread.so.1.76.0 (0x00007f6fd42e9000)
	libboost_filesystem.so.1.76.0 => /home/tqm-dev/projects/catapult-client/_deps/boost/lib/libboost_filesystem.so.1.76.0 (0x00007f6fd42c8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6fd42bb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6fd416c000)

**Comment by tqm-dev** [comment]
Fixed with adding below path to LD_LIBRARY_PATH
 $HOME/projects/catapult-client/_deps/mongodb/lib/:$HOME/projects/catapult-client/_deps/zeromq/lib/

$ ./catapult.broker ..

But getting another error:
```
2021-11-30 00:36:12.702119 0x00007fe3b586f700: <error> (src::MongoErrorPolicy.cpp@94) Throwing exception: error deleting (at least) transactions from [unconfirmedTransactions] collection (1 expected, 0 actual) 
2021-11-30 00:36:12.702466 0x00007fe3b586f700: <fatal> (process::ProcessMain.cpp@75) 
thread: 1 (broker) work
unhandled exception while running local node!
../extensions/mongo/src/MongoErrorPolicy.cpp(94): Throw in function void catapult::mongo::MongoErrorPolicy::formatMessageAndThrow(const char*, uint64_t, uint64_t, const string&) const
Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
std::exception::what: error deleting (at least) transactions from [unconfirmedTransactions] collection (1 expected, 0 actual)

```
How do I fix it ?

Thank you .

**Comment by Jaguar0625** [comment]
did you run ./catapult.recovery?

**Comment by tqm-dev** [comment]
@Jaguar0625 

> did you run ./catapult.recovery?

Getting the other error :

2021-11-30 09:15:43.334040 0x00007f401ae0eac0: <error> (cache_db::RocksDatabase.cpp@169) Throwing exception: couldn't open database (../data/statedb/HashCache, IO error: While lock file: ../data/statedb/HashCache/LOCK: Resource temporarily unavailable) 
2021-11-30 09:15:43.334254 0x00007f401ae0eac0: <error> (plugins::PluginLoader.cpp@42) Throwing exception: ../src/catapult/cache_db/RocksDatabase.cpp(169): Throw in function catapult::cache::RocksDatabase::RocksDatabase(const catapult::cache::RocksDatabaseSettings&)
Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
std::exception::what: couldn't open database
[catapult::ErrorParam1*] = ../data/statedb/HashCache
[catapult::ErrorParam2*] = IO error: While lock file: ../data/statedb/HashCache/LOCK: Resource temporarily unavailable
 
2021-11-30 09:15:43.334476 0x00007f401ae0eac0: <fatal> (local::HostUtils.h@43) unhandled exception while boot!
../src/catapult/plugins/PluginLoader.cpp(42): Throw in function void catapult::plugins::{anonymous}::LoadPlugin(catapult::plugins::PluginManager&, const catapult::plugins::PluginModule&, const char*)
Dynamic exception type: boost::wrapexcept<catapult::plugins::plugin_load_error>
std::exception::what: ../src/catapult/cache_db/RocksDatabase.cpp(169): Throw in function catapult::cache::RocksDatabase::RocksDatabase(const catapult::cache::RocksDatabaseSettings&)
Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
std::exception::what: couldn't open database
[catapult::ErrorParam1*] = ../data/statedb/HashCache
[catapult::ErrorParam2*] = IO error: While lock file: ../data/statedb/HashCache/LOCK: Resource temporarily unavailable

 
2021-11-30 09:15:43.334508 0x00007f401ae0eac0: <error> (local::HostUtils.h@44) Throwing exception: ../src/catapult/cache_db/RocksDatabase.cpp(169): Throw in function catapult::cache::RocksDatabase::RocksDatabase(const catapult::cache::RocksDatabaseSettings&)
Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
std::exception::what: couldn't open database
[catapult::ErrorParam1*] = ../data/statedb/HashCache
[catapult::ErrorParam2*] = IO error: While lock file: ../data/statedb/HashCache/LOCK: Resource temporarily unavailable
 
2021-11-30 09:15:43.334535 0x00007f401ae0eac0: <fatal> (process::ProcessMain.cpp@75) 
thread: recovery catapu
unhandled exception while running local node!
../src/catapult/local/HostUtils.h(44): Throw in function std::unique_ptr<_Tp> catapult::local::CreateAndBootHost(TArgs&& ...) [with THost = catapult::local::{anonymous}::DefaultRecoveryOrchestrator; TArgs = {std::unique_ptr<catapult::extensions::ProcessBootstrapper, std::default_delete<catapult::extensions::ProcessBootstrapper> >}]
Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
std::exception::what: ../src/catapult/cache_db/RocksDatabase.cpp(169): Throw in function catapult::cache::RocksDatabase::RocksDatabase(const catapult::cache::RocksDatabaseSettings&)
Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
std::exception::what: couldn't open database
[catapult::ErrorParam1*] = ../data/statedb/HashCache
[catapult::ErrorParam2*] = IO error: While lock file: ../data/statedb/HashCache/LOCK: Resource temporarily unavailable

**Comment by Jaguar0625** [comment]
it seems you're trying to run it while the server is running. that is not supported, and you'll need to resync now.

**Comment by tqm-dev** [comment]
> it seems you're trying to run it while the server is running. that is not supported, and you'll need to resync now.

Ended up it works fine !
thank you for your support.
