### ISSUE TITLE
on-chain file upload?

### ISSUE THREAD

**Issue by spreebits** [symbol/catapult-client#176]
It seems to be possible not only to store tokens in the blockchain, but also illegal or copyrighted content can apparently be stored in the symbol blockchain:

https://twitter.com/peersyst/status/1402948911145304065

This can be a problem for node operators. Even if something like this becomes public, that problematic content was uploaded there hurts the whole project.

There should be an option for node operators to control if they want this or not?

**Comment by spreebits** [comment]
In my opinion, tokens and metadata should be managed in the blockchain, not complete files. A limit on file size, for example? That only tokens fit in there.

Should the blockchain really become a data store now? How big should the files be? If I now start uploading 4K UHD files? Or someone's porn collection, whether legal or illegal?

**Comment by gimer** [comment]
what _files_? symbol does not allow storing files _per se_

message has limit of 1024 bytes (`maxMessageSize = 1024`), even in nis1 you could have additional msgs per transaction (I don't remember what was the limit now).

metadata has network limit of (`maxValueSize = 1024`)

P.S. my question about virus signature was valid: it happened already long time ago, that somebody posted special transaction in bitcoin, that triggered AVs on windows - how does that differ from posting any other content?

**Comment by spreebits** [comment]
Then I must be misunderstanding something here, or false claims are being made in the tweets: 

https://twitter.com/peersyst/status/1402948907835985928

I do not use virus programs. And also no Windows.

**Comment by gimer** [comment]
I assume the issue can be closed?
