### ISSUE TITLE
Dynamic transaction amounts based on metadata values and mosaic balances

### ISSUE THREAD

**Issue by PaulRieger** [symbol/catapult-client#181]
**Problem**: Catapult has a great state machine but limited state transition capabilities. Currently, it is not possible to reference metadata values or mosaic balances to influence the future state.

**Proposal**: Dynamic amounts that can utilize a limited set of operators and references to metadata keys and mosaic balances.

**Example**: A constant product market maker where tx amounts depend on the available mosaic balance available at the time of the transaction inclusion into the block (`y * x = k`). Without the ability to reference the current state, it is impossible to keep `k` constant.

I.e. `amount = poolAccountRef.mosaics.dhp - (poolAccountRef.mosaics.xym * poolAccountRef.mosaics.dhp / (poolAccountRef.mosaics.xym + 100))`

**Comment by gimer** [comment]
@0x6861746366574 what's your take on this one?

**Comment by 0x6861746366574** [comment]
Thanks for your feedback, @PaulRieger. I quite like the idea! 

Could you please make a proposal [here](https://github.com/symbol/NIP)? The catapult-client issue list is for any bugs or issues relating to the _client_ itself; or for review of a plugin submitted as a PR. Anything relating to the Symbol network standards (which is implemented by all clients in the network) should be filed as a NIP. 

I'm happy to help with the NIP creation via [Discord.](https://www.discord.gg/xymcity

**Comment by 0x6861746366574** [comment]
Closing this as it's not a catapult-client bug or issue. Looking forward to your proposal, @PaulRieger!
