### ISSUE TITLE
restrictions on metadata

### ISSUE THREAD

**Issue by jabo38** [symbol/catapult-client#187]
I tried to do a restriction on an account for metadata. http://explorer.testnet.symboldev.network/transactions/A8F96095389286636BCDFCC5C9DF73BE898F9EBBDFF230B60DD5C86F9143FDBB

Since that time I've been able to do incoming, outgoing, and to itself metadata txs so I'm not sure if anything is being restricted. http://explorer.testnet.symboldev.network/accounts/TCQRS6YELTICU24IO4K4M5YJW7C552YT7372AMQ

**Comment by Jaguar0625** [comment]
currently, restrictions only apply to top-level (not embedded) transactions

**Comment by jabo38** [comment]
okay
