### ISSUE TITLE
Why is the gas returned by wallet and api different?

### ISSUE THREAD

**Issue by qlfgggggg** [symbol/catapult-client#214]
![image](https://user-images.githubusercontent.com/43543840/148638318-50d35fc3-2965-4743-ac4b-8a8a5f088e12.png)
![image](https://user-images.githubusercontent.com/43543840/148638340-3be581e3-3f99-446d-a6bb-e15651b383ea.png)

**Comment by Jaguar0625** [comment]
REST is showing the maximum amount that the signer is willing to pay.

Whe wallet/explorer is showing the actual amount paid, which is calculated by transaction.size * meta.feeMultiplier (176 * 5681).
